name: waiterapr04
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  http: ^1.3.0
  flutter_launcher_icons: ^0.14.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter Launcher Icons configuration (root level)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.JPEG"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.JPEG