name: waiter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  logger: ^2.5.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.JPEG"  # This should point to your actual image file

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpeg
